//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Data", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Representante de la Organización.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estoy de acuerdo.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alertar después (días).
        /// </summary>
        internal static string AlertAfter {
            get {
                return ResourceManager.GetString("AlertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alertar antes (días).
        /// </summary>
        internal static string AlertBefore {
            get {
                return ResourceManager.GetString("AlertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alertar al inicio?.
        /// </summary>
        internal static string AlertOnStart {
            get {
                return ResourceManager.GetString("AlertOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alertas.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos anexos.
        /// </summary>
        internal static string Annexes {
            get {
                return ResourceManager.GetString("Annexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio de facturación.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Promedio].
        /// </summary>
        internal static string ChartCO2AvgMonthly {
            get {
                return ResourceManager.GetString("ChartCO2AvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Totales por Protocolos].
        /// </summary>
        internal static string ChartCO2CompositionByProtocols {
            get {
                return ResourceManager.GetString("ChartCO2CompositionByProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Totales por Sitio].
        /// </summary>
        internal static string ChartCO2CompositionBySites {
            get {
                return ResourceManager.GetString("ChartCO2CompositionBySites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Total por Tipos].
        /// </summary>
        internal static string ChartCO2CompositionByTypes {
            get {
                return ResourceManager.GetString("ChartCO2CompositionByTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Suma].
        /// </summary>
        internal static string ChartCO2SumMonthly {
            get {
                return ResourceManager.GetString("ChartCO2SumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumos [Totales por Tipos].
        /// </summary>
        internal static string ChartCompositionByTypes {
            get {
                return ResourceManager.GetString("ChartCompositionByTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad [Promedio].
        /// </summary>
        internal static string ChartElectricityAvgMonthly {
            get {
                return ResourceManager.GetString("ChartElectricityAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad [Valores Cargados].
        /// </summary>
        internal static string ChartElectricityLoadedSerie {
            get {
                return ResourceManager.GetString("ChartElectricityLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad [Suma].
        /// </summary>
        internal static string ChartElectricitySumMonthly {
            get {
                return ResourceManager.GetString("ChartElectricitySumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustibles [Promedio].
        /// </summary>
        internal static string ChartFuelAvgMonthly {
            get {
                return ResourceManager.GetString("ChartFuelAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustibles [Valores Cargados].
        /// </summary>
        internal static string ChartFuelLoadedSerie {
            get {
                return ResourceManager.GetString("ChartFuelLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustibles [Suma].
        /// </summary>
        internal static string ChartFuelSumMonthly {
            get {
                return ResourceManager.GetString("ChartFuelSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficos.
        /// </summary>
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficos [Composición].
        /// </summary>
        internal static string ChartsCompositions {
            get {
                return ResourceManager.GetString("ChartsCompositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficos [Evolución].
        /// </summary>
        internal static string ChartsMonthlyEvolutions {
            get {
                return ResourceManager.GetString("ChartsMonthlyEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte [Promedio].
        /// </summary>
        internal static string ChartTransportAvgMonthly {
            get {
                return ResourceManager.GetString("ChartTransportAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte [Valores Cargados].
        /// </summary>
        internal static string ChartTransportLoadedSerie {
            get {
                return ResourceManager.GetString("ChartTransportLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte [Suma].
        /// </summary>
        internal static string ChartTransportSumMonthly {
            get {
                return ResourceManager.GetString("ChartTransportSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residuos [Promedio].
        /// </summary>
        internal static string ChartWasteAvgMonthly {
            get {
                return ResourceManager.GetString("ChartWasteAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residuos [Valores Cargados].
        /// </summary>
        internal static string ChartWasteLoadedSerie {
            get {
                return ResourceManager.GetString("ChartWasteLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residuos [Suma].
        /// </summary>
        internal static string ChartWasteSumMonthly {
            get {
                return ResourceManager.GetString("ChartWasteSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua [Promedio].
        /// </summary>
        internal static string ChartWaterAvgMonthly {
            get {
                return ResourceManager.GetString("ChartWaterAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua [Valores Cargados].
        /// </summary>
        internal static string ChartWaterLoadedSerie {
            get {
                return ResourceManager.GetString("ChartWaterLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua [Suma].
        /// </summary>
        internal static string ChartWaterSumMonthly {
            get {
                return ResourceManager.GetString("ChartWaterSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma preferido.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoger una Foto.
        /// </summary>
        internal static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente (Sitios de terceros).
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2.
        /// </summary>
        internal static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de CO2.
        /// </summary>
        internal static string CO2Generation {
            get {
                return ResourceManager.GetString("CO2Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límites de Generación de CO2.
        /// </summary>
        internal static string CO2GenerationLimit {
            get {
                return ResourceManager.GetString("CO2GenerationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de CO2 por Unidad Monetaria.
        /// </summary>
        internal static string CO2GenerationLimitByMoney {
            get {
                return ResourceManager.GetString("CO2GenerationLimitByMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de CO2 por Unidad de Área.
        /// </summary>
        internal static string CO2GenerationLimitByMts {
            get {
                return ResourceManager.GetString("CO2GenerationLimitByMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total CO2.
        /// </summary>
        internal static string CO2Total {
            get {
                return ResourceManager.GetString("CO2Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kg CO2e.
        /// </summary>
        internal static string CO2Unit {
            get {
                return ResourceManager.GetString("CO2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organización.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Organización.
        /// </summary>
        internal static string CompanyModify {
            get {
                return ResourceManager.GetString("CompanyModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumo.
        /// </summary>
        internal static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límites de Consumo.
        /// </summary>
        internal static string ConsumptionMonthlyLimit {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumo por Unidad Monetaria.
        /// </summary>
        internal static string ConsumptionMonthlyLimitByMoney {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimitByMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumo por Unidad de Área.
        /// </summary>
        internal static string ConsumptionMonthlyLimitByMts {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimitByMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer mas.
        /// </summary>
        internal static string CookieGotoPage {
            get {
                return ResourceManager.GetString("CookieGotoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2020 EcoCyclus. Todos los derechos reservados. Ninguna parte de este sitio puede reproducirse sin nuestro permiso por escrito..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Seguridad.
        /// </summary>
        internal static string CreditCardCode {
            get {
                return ResourceManager.GetString("CreditCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del Titular de la Tarjeta.
        /// </summary>
        internal static string CreditCardHolderInfo {
            get {
                return ResourceManager.GetString("CreditCardHolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la Tarjeta de Crédito.
        /// </summary>
        internal static string CreditCardInfo {
            get {
                return ResourceManager.GetString("CreditCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero de Control.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor de Emisión Predeterminado.
        /// </summary>
        internal static string DefaultEF {
            get {
                return ResourceManager.GetString("DefaultEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Predeterminada.
        /// </summary>
        internal static string DefaultUnit {
            get {
                return ResourceManager.GetString("DefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desviación.
        /// </summary>
        internal static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor de Emisión CO2 .
        /// </summary>
        internal static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del Factor de Emisión.
        /// </summary>
        internal static string EFDescription {
            get {
                return ResourceManager.GetString("EFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores de Emisión CO2.
        /// </summary>
        internal static string EFs {
            get {
                return ResourceManager.GetString("EFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Factores de Emisión para éste Sitio.
        /// </summary>
        internal static string EFsLink {
            get {
                return ResourceManager.GetString("EFsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad (kW/h).
        /// </summary>
        internal static string ElectricityUnits {
            get {
                return ResourceManager.GetString("ElectricityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reingresar Correo Electrónico.
        /// </summary>
        internal static string EmailReytpe {
            get {
                return ResourceManager.GetString("EmailReytpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo electrónico debe ser único.
        /// </summary>
        internal static string EmailUniqueMessage {
            get {
                return ResourceManager.GetString("EmailUniqueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Vencimiento.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a PDF.
        /// </summary>
        internal static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su nombre.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Valor.
        /// </summary>
        internal static string FirstValue {
            get {
                return ResourceManager.GetString("FirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El primer valor de lectura del medidor es la línea de base para el dispositivo y por lo tanto no generará consumos ni emisiones..
        /// </summary>
        internal static string FirstValueWarning {
            get {
                return ResourceManager.GetString("FirstValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie (m2).
        /// </summary>
        internal static string FloorSpace {
            get {
                return ResourceManager.GetString("FloorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2020 EcoCyclus. Todos los derechos reservados. Ninguna parte de este sitio puede reproducirse sin nuestro permiso por escrito..
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia de Carga Predeterminada.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustibles.
        /// </summary>
        internal static string Fuels {
            get {
                return ResourceManager.GetString("Fuels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustibles (lt).
        /// </summary>
        internal static string FuelsUnits {
            get {
                return ResourceManager.GetString("FuelsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Combustible.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a soporte@ecocyclus.com.
        /// </summary>
        internal static string HelpDeskMailAddress {
            get {
                return ResourceManager.GetString("HelpDeskMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe! No hay información de ayuda para este elemento..
        /// </summary>
        internal static string HelpEmpty {
            get {
                return ResourceManager.GetString("HelpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (?).
        /// </summary>
        internal static string HelpPostfix {
            get {
                return ResourceManager.GetString("HelpPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        internal static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las imágenes deben tener menos de [size] bytes y una extensión de archivo válida (jpg, png, gif or bmp)..
        /// </summary>
        internal static string ImageFormat {
            get {
                return ResourceManager.GetString("ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Español.
        /// </summary>
        internal static string InDefaultLanguage {
            get {
                return ResourceManager.GetString("InDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información!.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        internal static string InitialDate {
            get {
                return ResourceManager.GetString("InitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectura de Inicio.
        /// </summary>
        internal static string InitialReading {
            get {
                return ResourceManager.GetString("InitialReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia del Intervalo.
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está Activo?.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Gerente de la Organización?.
        /// </summary>
        internal static string IsCompanyManager {
            get {
                return ResourceManager.GetString("IsCompanyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Gerente del Sitio?.
        /// </summary>
        internal static string IsManager {
            get {
                return ResourceManager.GetString("IsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Operador del Sitio?.
        /// </summary>
        internal static string IsOperator {
            get {
                return ResourceManager.GetString("IsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es un medidor físico?.
        /// </summary>
        internal static string IsPhysical {
            get {
                return ResourceManager.GetString("IsPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Público?.
        /// </summary>
        internal static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Lector?.
        /// </summary>
        internal static string IsReader {
            get {
                return ResourceManager.GetString("IsReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Ida y Vuelta?.
        /// </summary>
        internal static string IsRoundtrip {
            get {
                return ResourceManager.GetString("IsRoundtrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI [CO2].
        /// </summary>
        internal static string KPIM2 {
            get {
                return ResourceManager.GetString("KPIM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m2.
        /// </summary>
        internal static string KPIM2Unit {
            get {
                return ResourceManager.GetString("KPIM2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI [CO2 por moneda].
        /// </summary>
        internal static string KPIMoney {
            get {
                return ResourceManager.GetString("KPIMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimo Registro.
        /// </summary>
        internal static string LastDate {
            get {
                return ResourceManager.GetString("LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimo Operador.
        /// </summary>
        internal static string LastOperator {
            get {
                return ResourceManager.GetString("LastOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimo Valor.
        /// </summary>
        internal static string LastValue {
            get {
                return ResourceManager.GetString("LastValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkEmail {
            get {
                return ResourceManager.GetString("lnkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkFacebook {
            get {
                return ResourceManager.GetString("lnkFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkTwitter {
            get {
                return ResourceManager.GetString("lnkTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Valores.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Cargados.
        /// </summary>
        internal static string LoadedSerie {
            get {
                return ResourceManager.GetString("LoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores Cargados.
        /// </summary>
        internal static string LoadGrid {
            get {
                return ResourceManager.GetString("LoadGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando ....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Actual:.
        /// </summary>
        internal static string LocationPrevious {
            get {
                return ResourceManager.GetString("LocationPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Seleccionada:.
        /// </summary>
        internal static string LocationSelected {
            get {
                return ResourceManager.GetString("LocationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localizador.
        /// </summary>
        internal static string Locator {
            get {
                return ResourceManager.GetString("Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvido su contraseña?.
        /// </summary>
        internal static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir conectado.
        /// </summary>
        internal static string LoginKeepMeLoggedIn {
            get {
                return ResourceManager.GetString("LoginKeepMeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerente.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerentes.
        /// </summary>
        internal static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos marcados con un * son información obligatoria!.
        /// </summary>
        internal static string MandatoryFieldExplanation {
            get {
                return ResourceManager.GetString("MandatoryFieldExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicaciones.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medidor.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medidores.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Medidor.
        /// </summary>
        internal static string MetersAdd {
            get {
                return ResourceManager.GetString("MetersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución.
        /// </summary>
        internal static string MonthlyEvolutions {
            get {
                return ResourceManager.GetString("MonthlyEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota Mensual.
        /// </summary>
        internal static string MonthlyFee {
            get {
                return ResourceManager.GetString("MonthlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meses.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Acceso.
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --/--/--.
        /// </summary>
        internal static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ítems para mostrar.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --/--/--.
        /// </summary>
        internal static string NoStartDate {
            get {
                return ResourceManager.GetString("NoStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operar.
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñe Actual.
        /// </summary>
        internal static string PasswordCurrent {
            get {
                return ResourceManager.GetString("PasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reingresar Contraseña.
        /// </summary>
        internal static string PasswordRetype {
            get {
                return ResourceManager.GetString("PasswordRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Pago.
        /// </summary>
        internal static string PaymentAdd {
            get {
                return ResourceManager.GetString("PaymentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar un pago para un período de tiempo anterior [currentFrom].
        /// </summary>
        internal static string PaymentAddFrom {
            get {
                return ResourceManager.GetString("PaymentAddFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar un pago para un período de tiempo posterior [currentTo].
        /// </summary>
        internal static string PaymentAddTo {
            get {
                return ResourceManager.GetString("PaymentAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El actual período permitido para cargar datos va desde [currentFrom] a [currentTo]..
        /// </summary>
        internal static string PaymentCurrentPeriod {
            get {
                return ResourceManager.GetString("PaymentCurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta.
        /// </summary>
        internal static string PaymentTypes {
            get {
                return ResourceManager.GetString("PaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desempeño.
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        internal static string PermissionsAvailable {
            get {
                return ResourceManager.GetString("PermissionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concedido.
        /// </summary>
        internal static string PermissionsGranted {
            get {
                return ResourceManager.GetString("PermissionsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        internal static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión Impresa.
        /// </summary>
        internal static string PrintableVersion {
            get {
                return ResourceManager.GetString("PrintableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EcoCyclus :: Sustainability Communities.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Perfil.
        /// </summary>
        internal static string ProfileModify {
            get {
                return ResourceManager.GetString("ProfileModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protocolos.
        /// </summary>
        internal static string Protocols {
            get {
                return ResourceManager.GetString("Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectura.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione el icono de ubicación..
        /// </summary>
        internal static string RegisterLocationWarning {
            get {
                return ResourceManager.GetString("RegisterLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave debe tener al menos 8 caracteres con una mayúscula, una minúscula y un número..
        /// </summary>
        internal static string RegisterPasswordWarning {
            get {
                return ResourceManager.GetString("RegisterPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al hacer clic en Registrarse, usted acepta nuestras &lt;ahref=&quot;/Registration/DataPolicy.aspx&quot;&gt;Condiciones &lt;/a&gt; y ha leído nuestra &lt;ahref=&quot;/Registration/DataPolicy.aspx&quot;&gt;Política de Uso de Datos&lt;/a&gt;, incluido el uso de cookies..
        /// </summary>
        internal static string RegistrationAgree {
            get {
                return ResourceManager.GetString("RegistrationAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de su organización.
        /// </summary>
        internal static string RegistrationCompanyName {
            get {
                return ResourceManager.GetString("RegistrationCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su correo electrónico.
        /// </summary>
        internal static string RegistrationEmail {
            get {
                return ResourceManager.GetString("RegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reingrese su correo electrónico.
        /// </summary>
        internal static string RegistrationEmailRetype {
            get {
                return ResourceManager.GetString("RegistrationEmailRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ubicación de su organización.
        /// </summary>
        internal static string RegistrationLocation {
            get {
                return ResourceManager.GetString("RegistrationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reingrese su contraseña.
        /// </summary>
        internal static string RegistrationPasswordRetype {
            get {
                return ResourceManager.GetString("RegistrationPasswordRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cerrar sesión.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ida y vuelta.
        /// </summary>
        internal static string Roundtrip {
            get {
                return ResourceManager.GetString("Roundtrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        internal static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Valores de Consumo.
        /// </summary>
        internal static string SetConsumption {
            get {
                return ResourceManager.GetString("SetConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Establecer Tabla para Carga.
        /// </summary>
        internal static string SetGrid {
            get {
                return ResourceManager.GetString("SetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Valores de Lectura.
        /// </summary>
        internal static string SetReading {
            get {
                return ResourceManager.GetString("SetReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de Alta (por única vez).
        /// </summary>
        internal static string SetupFee {
            get {
                return ResourceManager.GetString("SetupFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya pagado.
        /// </summary>
        internal static string SetupFeePaid {
            get {
                return ResourceManager.GetString("SetupFeePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string SignOff {
            get {
                return ResourceManager.GetString("SignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitio.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string SiteClose {
            get {
                return ResourceManager.GetString("SiteClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        internal static string SiteClosed {
            get {
                return ResourceManager.GetString("SiteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizado.
        /// </summary>
        internal static string SiteFinished {
            get {
                return ResourceManager.GetString("SiteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string SiteLive {
            get {
                return ResourceManager.GetString("SiteLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Activo.
        /// </summary>
        internal static string SiteLiveStatus {
            get {
                return ResourceManager.GetString("SiteLiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Cargando.
        /// </summary>
        internal static string SiteLoadStatus {
            get {
                return ResourceManager.GetString("SiteLoadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string SiteModify {
            get {
                return ResourceManager.GetString("SiteModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string SiteOpen {
            get {
                return ResourceManager.GetString("SiteOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abierto.
        /// </summary>
        internal static string SiteOpened {
            get {
                return ResourceManager.GetString("SiteOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string SiteRemove {
            get {
                return ResourceManager.GetString("SiteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitios.
        /// </summary>
        internal static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Sitio.
        /// </summary>
        internal static string SitesAdd {
            get {
                return ResourceManager.GetString("SitesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string SiteType {
            get {
                return ResourceManager.GetString("SiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bien hecho!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suma.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        internal static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Objetivos.
        /// </summary>
        internal static string TargetsModify {
            get {
                return ResourceManager.GetString("TargetsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Nuevos Valores.
        /// </summary>
        internal static string TargetsNewValues {
            get {
                return ResourceManager.GetString("TargetsNewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervalo.
        /// </summary>
        internal static string TimeUnit {
            get {
                return ResourceManager.GetString("TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        internal static string TimeUnitDay {
            get {
                return ResourceManager.GetString("TimeUnitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        internal static string TimeUnitMonth {
            get {
                return ResourceManager.GetString("TimeUnitMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período.
        /// </summary>
        internal static string TimeUnitPeriod {
            get {
                return ResourceManager.GetString("TimeUnitPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        internal static string TimeUnitYear {
            get {
                return ResourceManager.GetString("TimeUnitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semana.
        /// </summary>
        internal static string TimeuUnitWeek {
            get {
                return ResourceManager.GetString("TimeuUnitWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traducciones.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Entrada.
        /// </summary>
        internal static string TransportInputType {
            get {
                return ResourceManager.GetString("TransportInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Transporte.
        /// </summary>
        internal static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte (km).
        /// </summary>
        internal static string TransportUnits {
            get {
                return ResourceManager.GetString("TransportUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Empleados.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitio Web.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las direcciones Url deben tener un formato válido (por ej.: http://www.yoursite.com).
        /// </summary>
        internal static string UrlFormat {
            get {
                return ResourceManager.GetString("UrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Usuario.
        /// </summary>
        internal static string UserModify {
            get {
                return ResourceManager.GetString("UserModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string UserRemove {
            get {
                return ResourceManager.GetString("UserRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Usuario.
        /// </summary>
        internal static string UsersAdd {
            get {
                return ResourceManager.GetString("UsersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de Carga Activo.
        /// </summary>
        internal static string ValidLoadRange {
            get {
                return ResourceManager.GetString("ValidLoadRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención! Solo puede cargar los datos con fechas dentro del período de validez de carga pagado para este sitio. El marco de tiempo actual válido es a partir de [from] a [to]..
        /// </summary>
        internal static string ValidLoadRangeExplanation {
            get {
                return ResourceManager.GetString("ValidLoadRangeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residuos.
        /// </summary>
        internal static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Residuo.
        /// </summary>
        internal static string WasteType {
            get {
                return ResourceManager.GetString("WasteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residuo (kg).
        /// </summary>
        internal static string WasteUnits {
            get {
                return ResourceManager.GetString("WasteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua (L).
        /// </summary>
        internal static string WaterUnits {
            get {
                return ResourceManager.GetString("WaterUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración (semanas).
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
