//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Data", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Representative.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I agree.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert After (days).
        /// </summary>
        internal static string AlertAfter {
            get {
                return ResourceManager.GetString("AlertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert Before (days).
        /// </summary>
        internal static string AlertBefore {
            get {
                return ResourceManager.GetString("AlertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert on Start?.
        /// </summary>
        internal static string AlertOnStart {
            get {
                return ResourceManager.GetString("AlertOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerts.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount (VAT Included).
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annex Data.
        /// </summary>
        internal static string Annexes {
            get {
                return ResourceManager.GetString("Annexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing Address.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Monthly Average].
        /// </summary>
        internal static string ChartCO2AvgMonthly {
            get {
                return ResourceManager.GetString("ChartCO2AvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Totals by Protocols].
        /// </summary>
        internal static string ChartCO2CompositionByProtocols {
            get {
                return ResourceManager.GetString("ChartCO2CompositionByProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Totals by Sites].
        /// </summary>
        internal static string ChartCO2CompositionBySites {
            get {
                return ResourceManager.GetString("ChartCO2CompositionBySites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Total by Types].
        /// </summary>
        internal static string ChartCO2CompositionByTypes {
            get {
                return ResourceManager.GetString("ChartCO2CompositionByTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 [Monthly Sum].
        /// </summary>
        internal static string ChartCO2SumMonthly {
            get {
                return ResourceManager.GetString("ChartCO2SumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption [Totals by Types].
        /// </summary>
        internal static string ChartCompositionByTypes {
            get {
                return ResourceManager.GetString("ChartCompositionByTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricity [Monthly Average].
        /// </summary>
        internal static string ChartElectricityAvgMonthly {
            get {
                return ResourceManager.GetString("ChartElectricityAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricity [Loaded Values].
        /// </summary>
        internal static string ChartElectricityLoadedSerie {
            get {
                return ResourceManager.GetString("ChartElectricityLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricity [Monthly Sum].
        /// </summary>
        internal static string ChartElectricitySumMonthly {
            get {
                return ResourceManager.GetString("ChartElectricitySumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuels [Monthly Average].
        /// </summary>
        internal static string ChartFuelAvgMonthly {
            get {
                return ResourceManager.GetString("ChartFuelAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuels [Loaded Values].
        /// </summary>
        internal static string ChartFuelLoadedSerie {
            get {
                return ResourceManager.GetString("ChartFuelLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuels [Monthly Sum].
        /// </summary>
        internal static string ChartFuelSumMonthly {
            get {
                return ResourceManager.GetString("ChartFuelSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charts.
        /// </summary>
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charts [Compositions].
        /// </summary>
        internal static string ChartsCompositions {
            get {
                return ResourceManager.GetString("ChartsCompositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charts [Monthly Evolution].
        /// </summary>
        internal static string ChartsMonthlyEvolutions {
            get {
                return ResourceManager.GetString("ChartsMonthlyEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport [Monthly Average].
        /// </summary>
        internal static string ChartTransportAvgMonthly {
            get {
                return ResourceManager.GetString("ChartTransportAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport [Loaded Values].
        /// </summary>
        internal static string ChartTransportLoadedSerie {
            get {
                return ResourceManager.GetString("ChartTransportLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport [Monthly Sum].
        /// </summary>
        internal static string ChartTransportSumMonthly {
            get {
                return ResourceManager.GetString("ChartTransportSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste [Monthly Average].
        /// </summary>
        internal static string ChartWasteAvgMonthly {
            get {
                return ResourceManager.GetString("ChartWasteAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste [Loaded Values].
        /// </summary>
        internal static string ChartWasteLoadedSerie {
            get {
                return ResourceManager.GetString("ChartWasteLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste [Monthly Sum].
        /// </summary>
        internal static string ChartWasteSumMonthly {
            get {
                return ResourceManager.GetString("ChartWasteSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water [Monthly Average].
        /// </summary>
        internal static string ChartWaterAvgMonthly {
            get {
                return ResourceManager.GetString("ChartWaterAvgMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water [Loaded Values].
        /// </summary>
        internal static string ChartWaterLoadedSerie {
            get {
                return ResourceManager.GetString("ChartWaterLoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water [Monthly Sum].
        /// </summary>
        internal static string ChartWaterSumMonthly {
            get {
                return ResourceManager.GetString("ChartWaterSumMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a preferred language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a Picture.
        /// </summary>
        internal static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2.
        /// </summary>
        internal static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Generation.
        /// </summary>
        internal static string CO2Generation {
            get {
                return ResourceManager.GetString("CO2Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Generation Limits.
        /// </summary>
        internal static string CO2GenerationLimit {
            get {
                return ResourceManager.GetString("CO2GenerationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Generation by Money Unit.
        /// </summary>
        internal static string CO2GenerationLimitByMoney {
            get {
                return ResourceManager.GetString("CO2GenerationLimitByMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Generation by Space Unit.
        /// </summary>
        internal static string CO2GenerationLimitByMts {
            get {
                return ResourceManager.GetString("CO2GenerationLimitByMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total CO2.
        /// </summary>
        internal static string CO2Total {
            get {
                return ResourceManager.GetString("CO2Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kg CO2e.
        /// </summary>
        internal static string CO2Unit {
            get {
                return ResourceManager.GetString("CO2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Organization.
        /// </summary>
        internal static string CompanyModify {
            get {
                return ResourceManager.GetString("CompanyModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption.
        /// </summary>
        internal static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly Consumtion Limits.
        /// </summary>
        internal static string ConsumptionMonthlyLimit {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption by Money Unit.
        /// </summary>
        internal static string ConsumptionMonthlyLimitByMoney {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimitByMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption by Space Unit.
        /// </summary>
        internal static string ConsumptionMonthlyLimitByMts {
            get {
                return ResourceManager.GetString("ConsumptionMonthlyLimitByMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read more.
        /// </summary>
        internal static string CookieGotoPage {
            get {
                return ResourceManager.GetString("CookieGotoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2020 EcoCyclus. All rights reserved. No part of this site may be reproduced without our written permission..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security Code.
        /// </summary>
        internal static string CreditCardCode {
            get {
                return ResourceManager.GetString("CreditCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card Holder Information.
        /// </summary>
        internal static string CreditCardHolderInfo {
            get {
                return ResourceManager.GetString("CreditCardHolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit Card Information.
        /// </summary>
        internal static string CreditCardInfo {
            get {
                return ResourceManager.GetString("CreditCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Emission Factor.
        /// </summary>
        internal static string DefaultEF {
            get {
                return ResourceManager.GetString("DefaultEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Unit.
        /// </summary>
        internal static string DefaultUnit {
            get {
                return ResourceManager.GetString("DefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deviation.
        /// </summary>
        internal static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Emission Factor.
        /// </summary>
        internal static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emission Factor Description.
        /// </summary>
        internal static string EFDescription {
            get {
                return ResourceManager.GetString("EFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO2 Emission Factors.
        /// </summary>
        internal static string EFs {
            get {
                return ResourceManager.GetString("EFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Emission Factors List for this Site.
        /// </summary>
        internal static string EFsLink {
            get {
                return ResourceManager.GetString("EFsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricity.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricity (kW/h).
        /// </summary>
        internal static string ElectricityUnits {
            get {
                return ResourceManager.GetString("ElectricityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retype email.
        /// </summary>
        internal static string EmailReytpe {
            get {
                return ResourceManager.GetString("EmailReytpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email address must be unique.
        /// </summary>
        internal static string EmailUniqueMessage {
            get {
                return ResourceManager.GetString("EmailUniqueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration Date.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export to PDF Format.
        /// </summary>
        internal static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firstname.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Value.
        /// </summary>
        internal static string FirstValue {
            get {
                return ResourceManager.GetString("FirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The first reading value of the meter is the baseline for the device and therefore will not generate neither consumption nor emissions..
        /// </summary>
        internal static string FirstValueWarning {
            get {
                return ResourceManager.GetString("FirstValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Floor Space (m2).
        /// </summary>
        internal static string FloorSpace {
            get {
                return ResourceManager.GetString("FloorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2020 EcoCyclus. All rights reserved. No part of this site may be reproduced without our written permission..
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Upload Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuels.
        /// </summary>
        internal static string Fuels {
            get {
                return ResourceManager.GetString("Fuels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuels (lt).
        /// </summary>
        internal static string FuelsUnits {
            get {
                return ResourceManager.GetString("FuelsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuel Type.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fullname.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a support@ecocyclus.com.
        /// </summary>
        internal static string HelpDeskMailAddress {
            get {
                return ResourceManager.GetString("HelpDeskMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry! There is no help information for this element..
        /// </summary>
        internal static string HelpEmpty {
            get {
                return ResourceManager.GetString("HelpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (?).
        /// </summary>
        internal static string HelpPostfix {
            get {
                return ResourceManager.GetString("HelpPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification.
        /// </summary>
        internal static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Images must have less than [size] bytes and a valid file extension (jpg, png, gif or bmp)..
        /// </summary>
        internal static string ImageFormat {
            get {
                return ResourceManager.GetString("ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In English.
        /// </summary>
        internal static string InDefaultLanguage {
            get {
                return ResourceManager.GetString("InDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information!.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial Date.
        /// </summary>
        internal static string InitialDate {
            get {
                return ResourceManager.GetString("InitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial Reading.
        /// </summary>
        internal static string InitialReading {
            get {
                return ResourceManager.GetString("InitialReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interval Frequency.
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Active?.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Organization Manager?.
        /// </summary>
        internal static string IsCompanyManager {
            get {
                return ResourceManager.GetString("IsCompanyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Site Manager?.
        /// </summary>
        internal static string IsManager {
            get {
                return ResourceManager.GetString("IsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Site Operator?.
        /// </summary>
        internal static string IsOperator {
            get {
                return ResourceManager.GetString("IsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is it a physical meter?.
        /// </summary>
        internal static string IsPhysical {
            get {
                return ResourceManager.GetString("IsPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Public?.
        /// </summary>
        internal static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Faciltiy Reader?.
        /// </summary>
        internal static string IsReader {
            get {
                return ResourceManager.GetString("IsReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Roundtrip?.
        /// </summary>
        internal static string IsRoundtrip {
            get {
                return ResourceManager.GetString("IsRoundtrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI [CO2 by area].
        /// </summary>
        internal static string KPIM2 {
            get {
                return ResourceManager.GetString("KPIM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m2.
        /// </summary>
        internal static string KPIM2Unit {
            get {
                return ResourceManager.GetString("KPIM2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI [CO2 by currency].
        /// </summary>
        internal static string KPIMoney {
            get {
                return ResourceManager.GetString("KPIMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Recorded.
        /// </summary>
        internal static string LastDate {
            get {
                return ResourceManager.GetString("LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Operator.
        /// </summary>
        internal static string LastOperator {
            get {
                return ResourceManager.GetString("LastOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Value.
        /// </summary>
        internal static string LastValue {
            get {
                return ResourceManager.GetString("LastValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkEmail {
            get {
                return ResourceManager.GetString("lnkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkFacebook {
            get {
                return ResourceManager.GetString("lnkFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkTwitter {
            get {
                return ResourceManager.GetString("lnkTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Values.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded Data.
        /// </summary>
        internal static string LoadedSerie {
            get {
                return ResourceManager.GetString("LoadedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded Values.
        /// </summary>
        internal static string LoadGrid {
            get {
                return ResourceManager.GetString("LoadGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading ....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Location: .
        /// </summary>
        internal static string LocationPrevious {
            get {
                return ResourceManager.GetString("LocationPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Location: .
        /// </summary>
        internal static string LocationSelected {
            get {
                return ResourceManager.GetString("LocationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locator.
        /// </summary>
        internal static string Locator {
            get {
                return ResourceManager.GetString("Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep me logged in.
        /// </summary>
        internal static string LoginKeepMeLoggedIn {
            get {
                return ResourceManager.GetString("LoginKeepMeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Managers.
        /// </summary>
        internal static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All fields marked with an * are mandatory information!.
        /// </summary>
        internal static string MandatoryFieldExplanation {
            get {
                return ResourceManager.GetString("MandatoryFieldExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locations.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meter.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Meter.
        /// </summary>
        internal static string MetersAdd {
            get {
                return ResourceManager.GetString("MetersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly Evolution.
        /// </summary>
        internal static string MonthlyEvolutions {
            get {
                return ResourceManager.GetString("MonthlyEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly Fee.
        /// </summary>
        internal static string MonthlyFee {
            get {
                return ResourceManager.GetString("MonthlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Access.
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --/--/--.
        /// </summary>
        internal static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is not items to display.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --/--/--.
        /// </summary>
        internal static string NoStartDate {
            get {
                return ResourceManager.GetString("NoStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operate.
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        internal static string PasswordCurrent {
            get {
                return ResourceManager.GetString("PasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retype password.
        /// </summary>
        internal static string PasswordRetype {
            get {
                return ResourceManager.GetString("PasswordRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Payment.
        /// </summary>
        internal static string PaymentAdd {
            get {
                return ResourceManager.GetString("PaymentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a payment for a period of time before [currentFrom].
        /// </summary>
        internal static string PaymentAddFrom {
            get {
                return ResourceManager.GetString("PaymentAddFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a payment for a period of time after [currentTo].
        /// </summary>
        internal static string PaymentAddTo {
            get {
                return ResourceManager.GetString("PaymentAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current period enabled for data loading goes from [currentFrom] to [currentTo]..
        /// </summary>
        internal static string PaymentCurrentPeriod {
            get {
                return ResourceManager.GetString("PaymentCurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payments.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card.
        /// </summary>
        internal static string PaymentTypes {
            get {
                return ResourceManager.GetString("PaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available.
        /// </summary>
        internal static string PermissionsAvailable {
            get {
                return ResourceManager.GetString("PermissionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Granted.
        /// </summary>
        internal static string PermissionsGranted {
            get {
                return ResourceManager.GetString("PermissionsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plate Number.
        /// </summary>
        internal static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printable Version.
        /// </summary>
        internal static string PrintableVersion {
            get {
                return ResourceManager.GetString("PrintableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EcoCyclus :: Sustainability Communities.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Profile.
        /// </summary>
        internal static string ProfileModify {
            get {
                return ResourceManager.GetString("ProfileModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protocols.
        /// </summary>
        internal static string Protocols {
            get {
                return ResourceManager.GetString("Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By clicking Sign Up, you agree to our &lt;a href=&quot;/Registration/DataPolicy.aspx&quot;&gt;Terms&lt;/a&gt; and that you have read our &lt;a href=&quot;/Registration/DataPolicy.aspx&quot;&gt;Data Use Policy&lt;/a&gt;..
        /// </summary>
        internal static string RegistrationAgree {
            get {
                return ResourceManager.GetString("RegistrationAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your organization´s name.
        /// </summary>
        internal static string RegistrationCompanyName {
            get {
                return ResourceManager.GetString("RegistrationCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your email address.
        /// </summary>
        internal static string RegistrationEmail {
            get {
                return ResourceManager.GetString("RegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retype your email address.
        /// </summary>
        internal static string RegistrationEmailRetype {
            get {
                return ResourceManager.GetString("RegistrationEmailRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your organization´s location.
        /// </summary>
        internal static string RegistrationLocation {
            get {
                return ResourceManager.GetString("RegistrationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retype your password.
        /// </summary>
        internal static string RegistrationPasswordRetype {
            get {
                return ResourceManager.GetString("RegistrationPasswordRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsible.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roundtrip.
        /// </summary>
        internal static string Roundtrip {
            get {
                return ResourceManager.GetString("Roundtrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        internal static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Consumption Values.
        /// </summary>
        internal static string SetConsumption {
            get {
                return ResourceManager.GetString("SetConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Load Grid.
        /// </summary>
        internal static string SetGrid {
            get {
                return ResourceManager.GetString("SetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Reading Values.
        /// </summary>
        internal static string SetReading {
            get {
                return ResourceManager.GetString("SetReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setup Fee (First Time Only).
        /// </summary>
        internal static string SetupFee {
            get {
                return ResourceManager.GetString("SetupFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already paid.
        /// </summary>
        internal static string SetupFeePaid {
            get {
                return ResourceManager.GetString("SetupFeePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        internal static string SignOff {
            get {
                return ResourceManager.GetString("SignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Site.
        /// </summary>
        internal static string SiteClose {
            get {
                return ResourceManager.GetString("SiteClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed Site.
        /// </summary>
        internal static string SiteClosed {
            get {
                return ResourceManager.GetString("SiteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished Site.
        /// </summary>
        internal static string SiteFinished {
            get {
                return ResourceManager.GetString("SiteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Live Site.
        /// </summary>
        internal static string SiteLive {
            get {
                return ResourceManager.GetString("SiteLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Live Status.
        /// </summary>
        internal static string SiteLiveStatus {
            get {
                return ResourceManager.GetString("SiteLiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Management Status.
        /// </summary>
        internal static string SiteLoadStatus {
            get {
                return ResourceManager.GetString("SiteLoadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Site.
        /// </summary>
        internal static string SiteModify {
            get {
                return ResourceManager.GetString("SiteModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Site.
        /// </summary>
        internal static string SiteOpen {
            get {
                return ResourceManager.GetString("SiteOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opened Site.
        /// </summary>
        internal static string SiteOpened {
            get {
                return ResourceManager.GetString("SiteOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Site.
        /// </summary>
        internal static string SiteRemove {
            get {
                return ResourceManager.GetString("SiteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sites.
        /// </summary>
        internal static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Site.
        /// </summary>
        internal static string SitesAdd {
            get {
                return ResourceManager.GetString("SitesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string SiteType {
            get {
                return ResourceManager.GetString("SiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Date.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sum.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Targets.
        /// </summary>
        internal static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Targets.
        /// </summary>
        internal static string TargetsModify {
            get {
                return ResourceManager.GetString("TargetsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter New Values.
        /// </summary>
        internal static string TargetsNewValues {
            get {
                return ResourceManager.GetString("TargetsNewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interval.
        /// </summary>
        internal static string TimeUnit {
            get {
                return ResourceManager.GetString("TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        internal static string TimeUnitDay {
            get {
                return ResourceManager.GetString("TimeUnitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        internal static string TimeUnitMonth {
            get {
                return ResourceManager.GetString("TimeUnitMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Period.
        /// </summary>
        internal static string TimeUnitPeriod {
            get {
                return ResourceManager.GetString("TimeUnitPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        internal static string TimeUnitYear {
            get {
                return ResourceManager.GetString("TimeUnitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week.
        /// </summary>
        internal static string TimeuUnitWeek {
            get {
                return ResourceManager.GetString("TimeuUnitWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translations.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input Type.
        /// </summary>
        internal static string TransportInputType {
            get {
                return ResourceManager.GetString("TransportInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport Type.
        /// </summary>
        internal static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport (km).
        /// </summary>
        internal static string TransportUnits {
            get {
                return ResourceManager.GetString("TransportUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Employees.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url addresses must have a valid format (i.e.: http://www.yoursite.com).
        /// </summary>
        internal static string UrlFormat {
            get {
                return ResourceManager.GetString("UrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify User.
        /// </summary>
        internal static string UserModify {
            get {
                return ResourceManager.GetString("UserModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove User.
        /// </summary>
        internal static string UserRemove {
            get {
                return ResourceManager.GetString("UserRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add User.
        /// </summary>
        internal static string UsersAdd {
            get {
                return ResourceManager.GetString("UsersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled Load Range .
        /// </summary>
        internal static string ValidLoadRange {
            get {
                return ResourceManager.GetString("ValidLoadRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attention! You can upload data with dates within the valid load period paid for this Site.  The current valid time frame is from [from] to [to]..
        /// </summary>
        internal static string ValidLoadRangeExplanation {
            get {
                return ResourceManager.GetString("ValidLoadRangeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste.
        /// </summary>
        internal static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste Type.
        /// </summary>
        internal static string WasteType {
            get {
                return ResourceManager.GetString("WasteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waste (kg).
        /// </summary>
        internal static string WasteUnits {
            get {
                return ResourceManager.GetString("WasteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water (L).
        /// </summary>
        internal static string WaterUnits {
            get {
                return ResourceManager.GetString("WaterUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration (Weeks).
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postal Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
